# Generated by Django 2.2.22 on 2021-12-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_customer_lineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='message',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
    ]
