# Generated by Django 2.2.22 on 2021-12-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20211212_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_Details',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='billing_address',
            new_name='home_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='customer',
            name='message',
            field=models.TextField(default='Remark'),
        ),
    ]
