# Generated by Django 2.2.22 on 2021-12-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20211212_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='home_address',
            new_name='billing_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.AlterField(
            model_name='customer',
            name='message',
            field=models.TextField(default='this is a default message.'),
        ),
    ]
