# Generated by Django 2.2.22 on 2021-12-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_auto_20211212_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='service',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
